### ISSUE TITLE
Explicitly Describe Common Internal Retention Time

### ISSUE THREAD

**Issue by DarioS** [OpenSWATH/documentation#7]
I can't find any mention in the documentation about if CiRT can be used for calibration. The workflow published last year briefly mentions them, but I'm not sure if I can use OpenSWATH to do that kind of analysis. In the list of required input files, I see "An assay library containing assays for all iRT peptides in TraML format.", which makes me guess that CiRT isn't feasible. It's unclear if this is required only for that particular example or for all SWATH analysis by OpenSWATH. I also searched the codebase for CiRT hoping for some variable names to contain that phrase and didn't get any results. Could a couple of sentences be added to the documentation making this explicit? Perhaps `OpenSwathRTNormalizer` needs to be used, but I'm confused if I can/should specify that to `OpenSwathWorkflow`.

**Comment by grosenberger** [comment]
This is a good suggestion and since we are currently working on improving the documentation, I will add a section about CiRT. CiRT can definitely be used with OpenSWATH (the original paper used OpenSWATH), but there are some parameters that are useful to be optimized. Those are described in the paper, but I will add them to the documentation as well.

**Comment by grosenberger** [comment]
Updated description: http://www.openswath.org/en/latest/docs/openswath_workflow.html#retention-time-normalization
